apiVersion: v1
kind: Service
metadata:
  name: projetogeral-api
  labels:
    app: projetogeral-api
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32600
  selector:
    app: projetogeral-api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: projetogeral-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: projetogeral-api
    spec:
      containers:
        - name: app
          image: "127.0.0.1:30400/projetogeral-api:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
